# Macro File
# called from hole_dead{,2,3}.mac
# calls deadLayer2.mac
# changes the hole depth then loops over dead layer

#set the hole depth
/TwoClover/det/Clover2/setHole1Depth {holeDepth} mm
/TwoClover/det/Clover2/setHole2Depth {holeDepth} mm
/TwoClover/det/Clover2/setHole3Depth {holeDepth} mm
/TwoClover/det/Clover2/setHole4Depth {holeDepth} mm

#loop over dead layer thickness
/control/loop deadLayer2.mac deadLayer 500 1500 100
